// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOlIy-9PwbzPr-c-bHVhJl1luKlNRtsZg',
    appId: '1:66996944111:web:52609477993489a129af1a',
    messagingSenderId: '66996944111',
    projectId: 'colony-1',
    authDomain: 'colony-1.firebaseapp.com',
    storageBucket: 'colony-1.firebasestorage.app',
    measurementId: 'G-NZFTW59VPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy4m-3KcTn8WVTAx_GTNCoA6WM2t4QLQ0',
    appId: '1:66996944111:android:5f5d37f83bebcf6629af1a',
    messagingSenderId: '66996944111',
    projectId: 'colony-1',
    storageBucket: 'colony-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_64L7izcku-9b_Gmic7h3fpi6V5McaxA',
    appId: '1:66996944111:ios:4085184e7675335629af1a',
    messagingSenderId: '66996944111',
    projectId: 'colony-1',
    storageBucket: 'colony-1.firebasestorage.app',
    iosBundleId: 'com.colony.colonyApp',
  );
}
